codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: nearest
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 2%
        informational: true
    patch:
      default:
        target: auto
        threshold: 2%
        informational: true

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: false
